"""Copy the manuscript figures from notebooks/models/figures/ to the manuscript.

The figures are generated by the CNN/RF notebooks and by
notebooks/manuscript/figures.ipynb into notebooks/models/figures/.
This script copies the subset used by the manuscript, renaming where the
manuscript uses a different file name.
"""

import os
import shutil

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, "../.."))
SRC_MANUSCRIPT = os.path.join(ROOT_DIR, "notebooks/manuscript/figures")
SRC_MODELS = os.path.join(ROOT_DIR, "notebooks/models/figures")
DST = os.path.join(
    os.path.expanduser("~"),
    "Clouds/cloud.retegan.org/Manuscripts/2026-Zecchi/manuscript/figures",
)

# Manuscript file name -> source file name in notebooks/models/figures/.
FIGURES = {
    "dataset_spectra.pdf": "dataset_spectra.pdf",
    "noise_spectra.pdf": "noise_spectra.pdf",
    "augmentation_comparison.pdf": "augmentation_comparison.pdf",
    "self_absorption_spectra.pdf": (
        "random_forest_classifier_with_incident_beam_self_absorption.pdf"
    ),
    "baseline_cm.pdf": "baseline_cm.pdf",
    "cnn_noise_denoising.pdf": "cnn_classifier_noise_denoising.pdf",
    "spectral_ablation.pdf": "spectral_ablation.pdf",
    "experimental_spectra.pdf": "experimental_spectra.pdf",
    "outlier_screening.pdf": "outlier_screening.pdf",
    "fdmnes_broadening.pdf": "fdmnes_broadening.pdf",
}
for dst_name, src_name in FIGURES.items():
    src_ms = os.path.join(SRC_MANUSCRIPT, src_name)
    src_mod = os.path.join(SRC_MODELS, src_name)
    if os.path.exists(src_ms):
        src = src_ms
    elif os.path.exists(src_mod):
        src = src_mod
    else:
        raise FileNotFoundError(
            f"Missing source figure in both manuscript and models figures: {src_name}"
        )
    shutil.copy2(src, os.path.join(DST, dst_name))
    print(f"{src_name} -> {dst_name}")
print(f"Copied {len(FIGURES)} figures to {DST}")
